# Generated by Django 6.0.7 on 2026-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
